config/routes.rb
RecipeMash::Application.routes.draw do

  get "staticpages/contact"

  root to: 'static_pages#home'
  
  resources :users
	resources :sessions, only:  [:new, :create, :destroy]

	match '/signup', to: "users#new"
	match '/signin', to: "sessions#new"
	match '/signout', to: "sessions#destroy", via: :delete

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :chicken, :dessert, :meat, :appetizer, :content, :title, :user_id, :vegetarian
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
	has_secure_password

  before_save { |user| user.email = email.downcase }
	before_save :create_remember_token

  validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
						uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: {minimum: 6}
	validates :password_confirmation, presence: true


private

	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64	
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		if signed_in?
			flash[:error] = "Already Signed in"
			redirect_to current_user
		else
			render 'new'
		end
	end

	def create
		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_back_or user	
		else
			flash.now[:error] = "Invalid email/password combination"
			render 'new'
		end
	end


	def destroy
		sign_out
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :signed_in_user, only: [:index, :edit, :show, :update, :destroy]
	before_filter :correct_user, only: [:edit, :update, :show, :destroy]

	def index
			redirect_to current_user
	end		

	
  def new
	  if signed_in?
      flash[:error] = "Already Signed in: Signout before signing Up as different User"
      redirect_to current_user
    else
     @user = User.new    
      render 'new'
    end
  end

	def edit
	end

	def update
		if (@user.update_attributes(params[:user])) 
			sign_in @user
			flash[:success] = "Your Profile is updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

 
  def show
      @user = User.find(params[:id])
  end  

  def create
     @user = User.new(params[:user])
     if @user.save
			 sign_in @user
			 flash[:success] = "Welcome to Recipe Mash"
       redirect_to @user
     else
       render 'new'
     end
  end

  def destroy
		 User.find(params[:id]).destroy
		 flash[:notice] = "Your Profile is deleted. We miss you"
		 redirect_to root_path
	end
		


	private
		
		def signed_in_user		
			unless signed_in?
				store_location
				redirect_to signin_url, notice: "Please sign in!! "
			end
		end

		def correct_user
			@user = User.find(params[:id])
			unless current_user?(@user) 
				flash[:error] = "Dont access other users info!!!!" 
				redirect_to root_url 
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
			base_title = "Recipe Mash"
			if page_title.empty?
				base_title
			else
				"#{base_title} | #{page_title}"
			end
	end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end
	
	def current_user?(user)
		user == current_user
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end	

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url
	end
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
	<div class="navbar-inner">
		<div class="container-fluid">
			<ul class="nav pull-left">
				<li class="brand"> Recipe Mash </li>
			</ul>
			<ul class="nav pull-right">
				<li> <%= link_to "Home", root_url %> </li>
			<% if signed_in? %>
				<li> <%= link_to "Profile", current_user %> </li>
				<li> <%= link_to "Log Out", signout_path, method: "delete" %> </li> 
			<% else %>
				<li> <%= link_to "Log In", signin_path %></li>
				<li> <%= link_to "Sign Up", signup_path %></li>
			<% end %>
				<li> <%= link_to "About", '#' %> </li>
			</ul
		</div>
	</div>
</div>

<div class="container-fluid">
	<% flash.each do |key,value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li> * <%= msg  %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/contact.html.erb
<h1>Recipes#contact</h1>
<p>Find me in app/views/recipes/contact.html.erb</p>

app/views/static_pages/home.html.erb
  <div class="bcontent">
     <table class="home"> 
       <tr>
         <th class="table-header"> Vegan </th>
         <th class="table-header" > Vegetarian  </th>
         <th class="table-header"> Desserts </th>
         <th class="table-header"> Chicken Dishes </th>
         <th class="table-header"> Beef/Pork Dishes </th>
       </tr>
       <tr>
         <td class="table-content"> Vegan lasagna </td>
         <td class="table-content"> Eggplant Curry </td>
         <td class="table-content"> Chocolate Sherbet </td>
         <td class="table-content"> Chicken tikka Masal </td>
         <td class="table-content"> Beef and por Fried Rice </td>
       </tr>
     </table> 
      
   </div>
</div>

app/views/users/edit.html.erb
<h1> Update Profile </h1>

<div class="row-fluid">
	<div class="span6 offset3">
		<%= render 'shared/error_messages' %> 
		<%= form_for(@user) do |f| %>
			<%= f.label :name %>
    	<%=	f.text_field :name %>
			
			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Save Changes", class: "btn btn-primary" %>
		<% end %>

		<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails">change</a>
	</div>
</div> 

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<div>
<div class="row-fluid">
<h1 class="span11 offset1">
  Sign-Up (to post the most yummy recipes)</h1>
</div>
<div class="row-fluid">
	<div class="span6 offset2">
	  <%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
     	<%= f.label :name %>
     	<%= f.text_field :name %>
    
			 <br /> 
    
			 <%= f.label :email %>
	     <%= f.text_field :email %>
	
			 <br />

			 <%= f.label :password %>
			 <%= f.password_field :password %>
	
			 <br />
	
			 <%= f.label :password_confirmation, "Confirmation" %>
			 <%= f.password_field :password_confirmation %>

     <br />
     <br />
    
     <%= f.submit "Create account", class: "btn btn-primary" %>

    <% end %>
	</div>

</div>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>

<div class="row-fluid">
 <div class="span8">
  <h1> 
	  <%= gravatar_for @user %>
	  <%= @user.name %>
  </h1>
 </div>

 <div class="span2 ">
		<%= button_to 'Edit Profile', edit_user_path(@user), method: :get, class: "btn btn-primary" %>
 </div>

 <div class="span2">
		<%= link_to 'Delete Profile', @user, method: :delete, data: { confirm: "Are You sure?"} , class: "btn btn-primary"  %>
 </div>

</div>